#!/usr/bin/env bash
# Generates app/Shared/Secrets.swift from the repo-root .env (never committed —
# both the output and .env are gitignored). Run after editing .env:
#   cd app && ./scripts/gen_secrets.sh
set -euo pipefail

cd "$(dirname "$0")/.."
ENV_FILE="../.env"
OUT="Shared/Secrets.swift"

[ -f "$ENV_FILE" ] || { echo "missing $ENV_FILE — copy .env.example and fill it in" >&2; exit 1; }

# shellcheck disable=SC1090
source "$ENV_FILE"
: "${SUPABASE_URL:?SUPABASE_URL missing from .env}"
: "${APP_SHARED_SECRET:?APP_SHARED_SECRET missing from .env}"

mkdir -p Shared
cat > "$OUT" <<EOF
// GENERATED by scripts/gen_secrets.sh from ../.env — do not edit, never commit.
import Foundation

enum Secrets {
    static let functionsBaseURL = URL(string: "${SUPABASE_URL}/functions/v1")!
    static let appSharedSecret = "${APP_SHARED_SECRET}"
}
EOF
echo "wrote $OUT"
